### PR TITLE
Support for ssl connection to mongo

### PR DESCRIPTION
**Pull request by Rajik**
Added ssl query parameter in the connection string while connecting securely to the mongo db.
This option can be configured by passing ssl option in the config file. The datatype of that option should be boolean.
**Example:** `ssl: true`

### CODE REVIEW

**Comment by emirotin** [comment]
Thanks for your contribution!
Can you please squash the commits (`git rebase develop -i`)?

**Comment by Rajik** [comment]
I have squashed the commits. Please verify them.
Thanks!

**Comment by emirotin** [comment]
Now there are 3 commits instead of 2, this is not squashing :)
BTW did you edit both files by hand?
Anyway I'll refactor it now, nevermind.

**Comment by emirotin** [comment]
To speedup things I've reimplemented your change by hand and published it as `0.5.2`.
Thanks for the PR again! I'm closing it now, please let me know if things work as expected.

**Pull request closed without merging**
